idf_component_register(SRCS main.c
                            global.c
                            system.c
                            ignition.c
                            sensors/ads.c
                            sensors/max.c
                            save_send.c
                        INCLUDE_DIRS ".")
